- name: Installing maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: Setting up app content
  ansible.builtin.import_tasks:
    file: app_setup.yml

- name: Downloading dependencies and building application
  ansible.builtin.shell: mvn clean package ;   mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: Setting up service
  ansible.builtin.import_task:
    file: conf_setup.yml

- name: Restarting Service
  ansible.builtin.import_task:
    file: service_setup.yml

- name: Installing mysql client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: loading schema
  ansible.builtin.import_task:
    file: mysql_schema.yml

- name: restarting Shipping service
  ansible.builtin.systemd:
    name: shipping
    state: restarted