- name: Setting up mongodb repo
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing MongoDB client
  ansible.builtin.dnf:
    name: mongodb-org-shell
    state: installed

- name: Loading schema from mongodb
  ansible.builtin.shell: mongo --host 172.31.26.173 </app/schema/catalogue.js
