- name: Setting up payment component
  ansible.builtin.dnf:
   name:
   - python36
   - gcc
   - python3-devel
  state: installed

- name: Setting up app content
  ansible.builtin.import_tasks:
    file: app_setup.yml

- name: Downloading dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Setting up configuration file
  ansible.builtin.import_tasks:
    file: conf_setup.yml

- name: Restarting service
  ansible.builtin.import_tasks:
   file: service_setup.yml
